# Generated by Django 3.0.3 on 2020-03-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
