# Generated by Django 3.0.4 on 2020-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200511_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no2',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
