# Generated by Django 3.0.4 on 2020-05-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200511_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_delete_admin', 'Can delete an admin'), ('can_make_admin', 'Can make a staff admin')]},
        ),
    ]
