# Generated by Django 3.0.4 on 2020-05-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200512_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_delete_admin', 'Can delete an admin'), ('can_promote_admin', 'Can promote a staff to admin'), ('can_demote_admin', 'Can demote admin to staff'), ('can_promote_superuser', 'Can promote a staff or admin to superuser')]},
        ),
    ]
