# Generated by Django 3.0.4 on 2020-04-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200416_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='order',
            new_name='order_items',
        ),
    ]
