# Generated by Django 3.0.4 on 2020-04-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200416_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='order_items',
            new_name='order',
        ),
    ]
