# Generated by Django 3.0.4 on 2020-04-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_auto_20200416_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
