# Generated by Django 3.0.4 on 2020-04-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_paymenthistory_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobile_no',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
