# Generated by Django 3.0.4 on 2020-04-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200425_0214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('size', 'product', 'category')},
        ),
    ]
