# Generated by Django 3.0.4 on 2020-04-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200428_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product.Color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='gsm',
            field=models.CharField(choices=[('', '----'), ('25', 25), ('30', 30), ('40', 40), ('50', 50), ('60', 60), ('70', 70), ('80', 80), ('90', 90), ('100', 100), ('110', 110)], max_length=4),
        ),
    ]
