# Generated by Django 3.0.4 on 2020-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200428_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='gsm',
            field=models.CharField(blank=True, choices=[(None, '----'), ('25 GSM', 25), ('30 GSM', 30), ('40 GSM', 40), ('50 GSM', 50), ('60 GSM', 60), ('70 GSM', 70), ('80 GSM', 80), ('90 GSM', 90), ('100 GSM', 100), ('110 GSM', 110)], max_length=8, null=True),
        ),
    ]
