# Generated by Django 3.0.4 on 2020-05-06 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200505_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2020, 5, 6, 0, 26, 26, 318309, tzinfo=utc))),
                ('shop_rent', models.FloatField(default=0.0)),
                ('shop_rent_per_product', models.FloatField(default=0.0)),
                ('electric_bill', models.FloatField(default=0.0)),
                ('electric_bill_per_product', models.FloatField(default=0.0)),
                ('others_bill', models.FloatField(default=0.0)),
                ('others_bill_per_product', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryManager',
        ),
    ]
