# Generated by Django 3.0.4 on 2020-05-06 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200506_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercost',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
