# Generated by Django 3.0.4 on 2020-05-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200506_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercost',
            old_name='electric_bill',
            new_name='electricity_bill',
        ),
        migrations.RenameField(
            model_name='othercost',
            old_name='electric_bill_per_product',
            new_name='electricity_bill_per_product',
        ),
    ]
