# Generated by Django 3.0.4 on 2020-05-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200506_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='profit_per_product',
            field=models.FloatField(default=0.0),
        ),
    ]
