# Generated by Django 3.0.4 on 2020-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_ordereditem_profit_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='purchase_price',
            field=models.FloatField(default=0.0),
        ),
    ]
