# Generated by Django 3.0.4 on 2020-05-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_suppliertransaction_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliertransaction',
            old_name='purchase_price',
            new_name='per_product_purchase_price',
        ),
    ]
