# Generated by Django 3.0.4 on 2020-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200509_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercost',
            name='employee_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='othercost',
            name='employee_cost_per_product',
            field=models.FloatField(default=0.0),
        ),
    ]
