# Generated by Django 3.0.4 on 2020-05-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0028_auto_20200511_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_sold_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
