# Generated by Django 3.0.4 on 2020-05-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='phone_no',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
