# Generated by Django 3.0.4 on 2020-05-09 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_auto_20200509_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolderReleaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releasing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('joining_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='is_active',
        ),
    ]
