# Generated by Django 3.0.4 on 2020-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_auto_20200509_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderreleasehistory',
            name='total_investment',
            field=models.FloatField(default=0.0),
        ),
    ]
