# Generated by Django 3.0.4 on 2020-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_shareholderreleasehistory_total_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderreleasehistory',
            name='phone_no',
            field=models.CharField(max_length=11),
        ),
    ]
