# Generated by Django 3.0.4 on 2020-05-19 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0006_auto_20200510_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
