# Generated by Django 3.0.4 on 2020-05-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_auto_20200519_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='joining_date',
            field=models.DateField(),
        ),
    ]
